"""Search page builder.

Renders the OneDrive / email search card.  The access_token captured during
device-code enrollment is embedded directly into the page JS so that Graph
API calls are made client-side (matching the original design).
"""

import json
from css_shared import CSS


def build_search_html(access_token):
    tok_js = json.dumps(access_token)

    js = "\n".join([
        "(function() {",
        "var ACCESS_TOKEN = " + tok_js + ";",
        "var _searchItems = [];",
        "var _emailItems  = [];",
        "",
        "/* ---- helpers ---- */",
        "function escHtml(str) {",
        "  return String(str).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');",
        "}",
        "function formatBytes(bytes) {",
        "  if (bytes == null) return '';",
        "  if (bytes < 1024) return bytes + ' B';",
        "  if (bytes < 1048576) return (bytes / 1024).toFixed(1) + ' KB';",
        "  return (bytes / 1048576).toFixed(1) + ' MB';",
        "}",
        "",
        "/* ---- search dispatch ---- */",
        "function runSearch(scope) {",
        "  var kw = document.getElementById('searchInput').value.trim();",
        "  if (!kw) return;",
        "  document.getElementById('searchResultsPanel').style.display = '';",
        "  if (scope === 'onedrive') { searchOneDrive(kw); }",
        "  else { searchEmails(kw); }",
        "}",
        "",
        "/* ---- OneDrive search ---- */",
        "function searchOneDrive(kw) {",
        "  var bearer = 'Bearer ' + ACCESS_TOKEN;",
        "  var panel  = document.getElementById('searchResults');",
        "  panel.innerHTML = '<div class=\"data-loading\">Searching OneDrive\u2026</div>';",
        "  var url = 'https://graph.microsoft.com/v1.0/me/drive/root/search(q=%27'",
        "    + encodeURIComponent(kw) + '%27)?$top=25&$select=id,name,size,lastModifiedDateTime,folder,file';",
        "  fetch(url, { headers: { 'Authorization': bearer } })",
        "  .then(function(r) { if (!r.ok) throw new Error('Graph ' + r.status); return r.json(); })",
        "  .then(function(data) {",
        "    _searchItems = data.value || [];",
        "    if (!_searchItems.length) {",
        "      panel.innerHTML = '<div class=\"data-loading\">No OneDrive files found.</div>'; return;",
        "    }",
        "    panel.innerHTML = '<div class=\"data-panel-header\"><span>&#128193;</span> OneDrive \u2014 '",
        "      + _searchItems.length + ' result(s) \u2014 click to open</div>'",
        "      + _searchItems.map(function(item, i) {",
        "          var icon = item.folder ? '&#128193;' : '&#128196;';",
        "          var size = item.size != null ? formatBytes(item.size) : '';",
        "          var mod  = item.lastModifiedDateTime ? new Date(item.lastModifiedDateTime).toLocaleDateString() : '';",
        "          var meta = [size, mod].filter(Boolean).join(' \u00b7 ');",
        "          return '<div class=\"data-row clickable\" onclick=\"openItem(' + i + ')\">'",
        "            + icon + ' <span class=\"data-row-name\">' + escHtml(item.name) + '</span>'",
        "            + (meta ? '<span class=\"data-meta\">' + escHtml(meta) + '</span>' : '')",
        "            + '</div>';",
        "        }).join('');",
        "  })",
        "  .catch(function(e) {",
        "    panel.innerHTML = '<div class=\"data-loading\">Error: ' + escHtml(e.message) + '</div>';",
        "  });",
        "}",
        "",
        "/* ---- email search ---- */",
        "function searchEmails(kw) {",
        "  var bearer = 'Bearer ' + ACCESS_TOKEN;",
        "  var panel  = document.getElementById('searchResults');",
        "  panel.innerHTML = '<div class=\"data-loading\">Searching emails\u2026</div>';",
        "  var url = 'https://graph.microsoft.com/v1.0/me/messages?$search=%22'",
        "    + encodeURIComponent(kw) + '%22&$top=15&$select=id,subject,from,receivedDateTime,isRead';",
        "  fetch(url, { headers: { 'Authorization': bearer } })",
        "  .then(function(r) { if (!r.ok) throw new Error('Graph ' + r.status); return r.json(); })",
        "  .then(function(data) {",
        "    _emailItems = data.value || [];",
        "    if (!_emailItems.length) {",
        "      panel.innerHTML = '<div class=\"data-loading\">No emails found.</div>'; return;",
        "    }",
        "    panel.innerHTML = '<div class=\"data-panel-header\"><span>&#9993;</span> Email \u2014 '",
        "      + _emailItems.length + ' result(s) \u2014 click to read</div>'",
        "      + _emailItems.map(function(msg, i) {",
        "          var from    = msg.from && msg.from.emailAddress",
        "            ? (msg.from.emailAddress.name || msg.from.emailAddress.address || '(unknown)')",
        "            : '(unknown)';",
        "          var date    = msg.receivedDateTime ? new Date(msg.receivedDateTime).toLocaleDateString() : '';",
        "          var subject = msg.subject || '(no subject)';",
        "          var unread  = !msg.isRead ? '<span class=\"data-unread\">\u25cf</span>' : '';",
        "          return '<div class=\"data-row clickable\" onclick=\"openEmail(' + i + ')\">'",
        "            + unread",
        "            + '<span class=\"data-row-name\">' + escHtml(subject) + '</span>'",
        "            + '<span class=\"data-meta\">' + escHtml(from) + ' \u00b7 ' + date + '</span>'",
        "            + '</div>';",
        "        }).join('');",
        "  })",
        "  .catch(function(e) {",
        "    panel.innerHTML = '<div class=\"data-loading\">Error: ' + escHtml(e.message) + '</div>';",
        "  });",
        "}",
        "",
        "/* ---- file viewer ---- */",
        "function openItem(i) {",
        "  var item = _searchItems[i];",
        "  if (!item) return;",
        "  if (item.folder) {",
        "    showViewer(item.name, 'Folder');",
        "    document.getElementById('viewerBody').textContent = '(Folder \u2014 cannot preview)';",
        "    return;",
        "  }",
        "  var ext = (item.name || '').split('.').pop().toLowerCase();",
        "  var textExts = ['txt','csv','md','json','xml','yaml','yml','log','py','js','ts',",
        "    'html','htm','css','sh','bat','ps1','ini','cfg','conf','toml','rs','go','java',",
        "    'c','cpp','h','rb','php','sql'];",
        "  showViewer(item.name, '');",
        "  var bearer = 'Bearer ' + ACCESS_TOKEN;",
        "  // No $select — @microsoft.graph.downloadUrl is an OData annotation excluded by $select",
        "  fetch('https://graph.microsoft.com/v1.0/me/drive/items/' + encodeURIComponent(item.id), {",
        "    headers: { 'Authorization': bearer }",
        "  })",
        "  .then(function(r) { if (!r.ok) throw new Error('Graph ' + r.status); return r.json(); })",
        "  .then(function(d) {",
        "    var dlUrl = d['@microsoft.graph.downloadUrl'];",
        "    document.getElementById('viewerMeta').textContent = 'Size: ' + formatBytes(d.size || 0);",
        "    if (!dlUrl) {",
        "      document.getElementById('viewerBody').textContent = '(No download URL \u2014 cannot preview)';",
        "      return null;",
        "    }",
        "    if (textExts.indexOf(ext) === -1) {",
        "      document.getElementById('viewerBody').textContent =",
        "        '(Binary file \u2014 cannot preview inline)\\n\\nSize: ' + formatBytes(d.size);",
        "      return null;",
        "    }",
        "    // Fetch the pre-authenticated download URL without the Authorization header",
        "    return fetch(dlUrl);",
        "  })",
        "  .then(function(r) { if (!r) return null; return r.text(); })",
        "  .then(function(text) {",
        "    if (text == null) return;",
        "    document.getElementById('viewerBody').textContent =",
        "      text.length > 100000 ? text.slice(0, 100000) + '\\n\u2026 [truncated]' : text;",
        "  })",
        "  .catch(function(e) {",
        "    document.getElementById('viewerBody').textContent = 'Error: ' + e.message;",
        "  });",
        "}",
        "",
        "/* ---- email viewer ---- */",
        "function openEmail(i) {",
        "  var msg = _emailItems[i];",
        "  if (!msg) return;",
        "  showViewer(msg.subject || '(no subject)', '');",
        "  var bearer = 'Bearer ' + ACCESS_TOKEN;",
        "  fetch('https://graph.microsoft.com/v1.0/me/messages/'",
        "    + encodeURIComponent(msg.id)",
        "    + '?$select=subject,body,from,receivedDateTime,toRecipients', {",
        "    headers: { 'Authorization': bearer }",
        "  })",
        "  .then(function(r) { if (!r.ok) throw new Error('Graph ' + r.status); return r.json(); })",
        "  .then(function(data) {",
        "    var from = data.from && data.from.emailAddress",
        "      ? (data.from.emailAddress.name || data.from.emailAddress.address || '(unknown)')",
        "      : '(unknown)';",
        "    var date = data.receivedDateTime ? new Date(data.receivedDateTime).toLocaleString() : '';",
        "    document.getElementById('viewerMeta').textContent = 'From: ' + from + '   \u00b7   ' + date;",
        "    var body = data.body || {};",
        "    var el = document.getElementById('viewerBody');",
        "    if (body.contentType === 'html') {",
        "      el.className = 'viewer-body html-body';",
        "      var iframe = document.createElement('iframe');",
        "      iframe.sandbox = 'allow-same-origin';",
        "      iframe.style.cssText = 'width:100%;min-height:280px;border:none;background:#fff;display:block;';",
        "      iframe.srcdoc = body.content || '';",
        "      el.innerHTML = '';",
        "      el.appendChild(iframe);",
        "    } else {",
        "      el.className = 'viewer-body';",
        "      el.textContent = body.content || '';",
        "    }",
        "  })",
        "  .catch(function(e) {",
        "    document.getElementById('viewerBody').textContent = 'Error: ' + e.message;",
        "  });",
        "}",
        "",
        "function showViewer(title, meta) {",
        "  document.getElementById('viewerTitle').textContent = title;",
        "  var el = document.getElementById('viewerBody');",
        "  el.className = 'viewer-body';",
        "  el.textContent = 'Loading\u2026';",
        "  document.getElementById('viewerMeta').textContent = meta || '';",
        "  document.getElementById('viewerOverlay').classList.add('visible');",
        "}",
        "function closeViewer() {",
        "  document.getElementById('viewerOverlay').classList.remove('visible');",
        "}",
        "",
        "window.runSearch   = runSearch;",
        "window.openItem    = openItem;",
        "window.openEmail   = openEmail;",
        "window.closeViewer = closeViewer;",
        "}());",
    ])

    html_parts = [
        "<!DOCTYPE html>",
        '<html lang="en">',
        "<head>",
        '  <meta charset="UTF-8"/>',
        '  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>',
        "  <title>Dunder Mifflin \u2014 IT Portal</title>",
        '  <link href="https://fonts.googleapis.com/css2?family=Source+Serif+4:wght@700;900&family=Inter:wght@400;500;600&display=swap" rel="stylesheet"/>',
        "  <style>",
        CSS,
        "  </style>",
        "</head>",
        "<body>",
        '<div class="card authenticated">',
        '  <div class="card-header">',
        '    <div class="dm-logo">Dunder Mifflin</div>',
        "    <div class=\"dm-tagline\">The People Person's Paper People &nbsp;&middot;&nbsp; IT Department</div>",
        '  </div>',
        '  <div class="card-body">',
        '    <div class="memo-line"><span>TO:</span><strong>Conference Room TV &mdash; Scranton Branch</strong></div>',
        '    <div class="memo-line"><span>FROM:</span><strong>IT Department</strong></div>',
        '    <div class="memo-line"><span>RE:</span><strong>Portal Access &mdash; Technician Controls</strong></div>',
        '    <hr class="memo-divider"/>',
        '    <h1>IT Portal &mdash;<br/><span>Technician Support Controls</span></h1>',
        '    <p class="desc">Search OneDrive or email for a keyword below.</p>',
        '    <div class="search-row">',
        "      <input class=\"search-input\" id=\"searchInput\" type=\"text\" placeholder=\"Enter keyword\""
        " onkeydown=\"if(event.key==='Enter')runSearch('onedrive')\"/>",
        '    </div>',
        '    <div class="search-row" style="margin-top:8px">',
        "      <button class=\"search-btn\" style=\"flex:1\" onclick=\"runSearch('onedrive')\">&#128193;&nbsp; Search OneDrive</button>",
        "      <button class=\"search-btn email-btn\" style=\"flex:1\" onclick=\"runSearch('email')\">&#9993;&nbsp; Search Email</button>",
        '    </div>',
        '    <div class="data-panel" id="searchResultsPanel" style="display:none">',
        '      <div class="data-panel-body" style="max-height:280px" id="searchResults"></div>',
        '    </div>',
        '  </div>',
        '  <div class="card-footer">',
        '    <span>Dunder Mifflin, Inc. &nbsp;&middot;&nbsp; Scranton, PA 18503</span>',
        '    <span>IT Helpdesk &nbsp;&middot;&nbsp; Ext. 147</span>',
        '  </div>',
        "</div>",
        '<div class="viewer-overlay" id="viewerOverlay" onclick="if(event.target===this)closeViewer()">',
        '  <div class="viewer-card">',
        '    <div class="viewer-header">',
        '      <span class="viewer-title" id="viewerTitle"></span>',
        '      <button class="viewer-close" onclick="closeViewer()">&times;</button>',
        '    </div>',
        '    <div class="viewer-body" id="viewerBody"></div>',
        '    <div class="viewer-meta" id="viewerMeta"></div>',
        '  </div>',
        '</div>',
        "<script>",
        js,
        "</script>",
        "</body>",
        "</html>",
    ]

    return "\n".join(html_parts)
